-- Quick Query: Get Aadhaar numbers of linked family members
-- Replace '387193279353' with your seed Aadhaar number

-- Option 1: From cache (if relationships are cached)
SELECT 
    seed_citizen.aadhaar_number AS seed_aadhaar,
    seed_citizen.full_name AS seed_name,
    related_citizen.aadhaar_number AS family_member_aadhaar,
    related_citizen.full_name AS family_member_name,
    frc.relationship_label AS relationship_type,
    frc.confidence,
    frc.source,
    frc.synced_at
FROM citizens seed_citizen
INNER JOIN family_relationships_cache frc ON seed_citizen.id = frc.citizen_id
INNER JOIN citizens related_citizen ON frc.related_citizen_id = related_citizen.id
WHERE seed_citizen.aadhaar_number = '387193279353'
  AND (frc.expires_at IS NULL OR frc.expires_at > CURRENT_TIMESTAMP)
ORDER BY frc.depth ASC, frc.confidence DESC;

-- Option 2: Address-based relationships (what backend uses when cache is empty)
-- This shows the relationships that are dynamically generated by address matching
SELECT 
    seed_citizen.aadhaar_number AS seed_aadhaar,
    seed_citizen.full_name AS seed_name,
    seed_citizen.address_line1 AS seed_address,
    seed_citizen.city AS seed_city,
    seed_citizen.district AS seed_district,
    seed_citizen.date_of_birth AS seed_dob,
    seed_citizen.gender AS seed_gender,
    related_citizen.aadhaar_number AS family_member_aadhaar,
    related_citizen.full_name AS family_member_name,
    related_citizen.date_of_birth AS member_dob,
    related_citizen.gender AS member_gender,
    CASE 
        -- Spouse detection: opposite gender, similar age (within 15 years)
        WHEN seed_citizen.gender != related_citizen.gender 
             AND seed_citizen.date_of_birth IS NOT NULL 
             AND related_citizen.date_of_birth IS NOT NULL
             AND ABS(EXTRACT(YEAR FROM AGE(seed_citizen.date_of_birth, related_citizen.date_of_birth))) <= 15
        THEN 'Spouse'
        -- Child detection: at least 15 years younger
        WHEN seed_citizen.date_of_birth IS NOT NULL 
             AND related_citizen.date_of_birth IS NOT NULL
             AND EXTRACT(YEAR FROM AGE(seed_citizen.date_of_birth, related_citizen.date_of_birth)) > 15
        THEN 'Child'
        ELSE 'Family Member'
    END AS relationship_type,
    CASE 
        WHEN seed_citizen.address_line1 IS NOT NULL 
             AND seed_citizen.address_line1 = related_citizen.address_line1 
        THEN 85
        WHEN seed_citizen.city IS NOT NULL 
             AND seed_citizen.city = related_citizen.city 
        THEN 70
        WHEN seed_citizen.district IS NOT NULL 
             AND seed_citizen.district = related_citizen.district 
        THEN 60
        ELSE 50
    END AS confidence,
    'ADDRESS_MATCH' AS source
FROM citizens seed_citizen
INNER JOIN citizens related_citizen ON (
    -- Same address (highest confidence)
    (seed_citizen.address_line1 IS NOT NULL 
     AND seed_citizen.address_line1 = related_citizen.address_line1)
    OR
    -- Same city (medium confidence)
    (seed_citizen.city IS NOT NULL 
     AND seed_citizen.city = related_citizen.city)
    OR
    -- Same district (lower confidence)
    (seed_citizen.district IS NOT NULL 
     AND seed_citizen.district = related_citizen.district)
)
WHERE seed_citizen.aadhaar_number = '387193279353'
  AND related_citizen.id != seed_citizen.id
  AND related_citizen.status = 'ACTIVE'
  AND seed_citizen.status = 'ACTIVE'
ORDER BY confidence DESC, relationship_type;

